/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.awt.event.KeyEvent;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import supermarket.Tools;

/**
 *
 * @author Mohamed
 */
public class reports extends javax.swing.JFrame {

    /**
     * Creates new form reports
     */
    public reports() {
        initComponents();
    }

    String username;

    public reports(String name) {
        initComponents();
        this.username = name;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_group = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        btn_back = new control.JMyButton();
        btn_print = new control.JMyButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rad_ID = new javax.swing.JRadioButton();
        rad_pro = new javax.swing.JRadioButton();
        rad_cat = new javax.swing.JRadioButton();
        rad_brand = new javax.swing.JRadioButton();
        rad_price = new javax.swing.JRadioButton();
        rad_qty = new javax.swing.JRadioButton();
        rad_total = new javax.swing.JRadioButton();
        txt_search = new control.JTextBox(20);
        btn_search = new control.JMyButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Category", "Brand", "Price", "Qty", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl);

        btn_back.setText("Back");
        btn_back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        btn_print.setText("Print report");
        btn_print.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Sales Report");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setText("Search by :");

        rad_ID.setBackground(new java.awt.Color(255, 255, 255));
        rad_ID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rad_ID.setText("ID");

        rad_pro.setBackground(new java.awt.Color(255, 255, 255));
        rad_pro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rad_pro.setText("Product");

        rad_cat.setBackground(new java.awt.Color(255, 255, 255));
        rad_cat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rad_cat.setText("Category");

        rad_brand.setBackground(new java.awt.Color(255, 255, 255));
        rad_brand.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rad_brand.setText("Brand");

        rad_price.setBackground(new java.awt.Color(255, 255, 255));
        rad_price.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rad_price.setText("Price");

        rad_qty.setBackground(new java.awt.Color(255, 255, 255));
        rad_qty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rad_qty.setText("QTY");

        rad_total.setBackground(new java.awt.Color(255, 255, 255));
        rad_total.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rad_total.setText("Total");

        txt_search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_searchKeyPressed(evt);
            }
        });

        btn_search.setText("Search");
        btn_search.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(258, 258, 258))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rad_ID)
                        .addGap(10, 10, 10)
                        .addComponent(rad_pro)
                        .addGap(10, 10, 10)
                        .addComponent(rad_cat)
                        .addGap(10, 10, 10)
                        .addComponent(rad_brand)
                        .addGap(10, 10, 10)
                        .addComponent(rad_price)
                        .addGap(10, 10, 10)
                        .addComponent(rad_qty)
                        .addGap(10, 10, 10)
                        .addComponent(rad_total)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rad_ID)
                        .addComponent(rad_pro)
                        .addComponent(rad_cat)
                        .addComponent(rad_brand)
                        .addComponent(rad_price)
                        .addComponent(rad_qty)
                        .addComponent(rad_total)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getCustom(String statement,JTable table) {
        db.database.fillToJTable(statement, table);
    }
    
    private void search() {
        String txtSer;
        String query = "";
        query = "SELECT * FROM `report_data` WHERE ";
        if (rad_ID.isSelected()) {
            txtSer = Tools.getnum(txt_search.getText());
            //Tools.msg(txtSer);
            query += "ID ";

        } else if (rad_pro.isSelected()) {
            txtSer = txt_search.getText();
            query += "Product ";
        } else if (rad_price.isSelected()){
            txtSer = Tools.getnum(txt_search.getText());
            query += "Price ";
        } else if (rad_brand.isSelected()){
            txtSer = txt_search.getText();
            query += "Brand ";
        } else if (rad_cat.isSelected()) {
            txtSer = txt_search.getText();
            query += "Category ";
        } else if (rad_qty.isSelected()) {
            txtSer = Tools.getnum(txt_search.getText());
            query += "QTY ";
        } else {
            txtSer = Tools.getnum(txt_search.getText());
            query += "Total ";
        }
        query += "like '%" + txtSer + "%'";
        getCustom(query, tbl);
    }
    
    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        main m = new main(username);
        m.setTitle("Main Menu");
        this.dispose();
        Tools.open(m);
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        // TODO add your handling code here:
        Tools.printReport(tbl, "Sales Report");
    }//GEN-LAST:event_btn_printActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        tbl.getTableHeader().setReorderingAllowed(false);
        btn_group.add(rad_ID);
        btn_group.add(rad_brand);
        btn_group.add(rad_cat);
        btn_group.add(rad_price);
        btn_group.add(rad_pro);
        btn_group.add(rad_qty);
        btn_group.add(rad_total);
        
        Tools.reportStyle(tbl);
        db.database.fillToJTable("report_data", tbl);

        //rp.select(tbl);
    }//GEN-LAST:event_formWindowOpened

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_btn_searchActionPerformed

    private void txt_searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            search();
        }
    }//GEN-LAST:event_txt_searchKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private control.JMyButton btn_back;
    private javax.swing.ButtonGroup btn_group;
    private control.JMyButton btn_print;
    private control.JMyButton btn_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rad_ID;
    private javax.swing.JRadioButton rad_brand;
    private javax.swing.JRadioButton rad_cat;
    private javax.swing.JRadioButton rad_price;
    private javax.swing.JRadioButton rad_pro;
    private javax.swing.JRadioButton rad_qty;
    private javax.swing.JRadioButton rad_total;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
