/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import static com.sun.tools.javac.tree.TreeInfo.name;
import entity.*;
import java.awt.event.KeyEvent;
import javax.swing.SwingUtilities;
import supermarket.Tools;

/**
 *
 * @author Mohamed
 */
public class stock extends javax.swing.JFrame {

    /**
     * Creates new form product
     */
    public stock() {
        initComponents();
        cmx_status.addItem("Active");
        cmx_status.addItem("InActive");
    }

    String username;

    public stock(String name) {
        initComponents();
        cmx_status.addItem("Active");
        cmx_status.addItem("InActive");
        this.username = name;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_group = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_ID = new control.JTextBox(20);
        jLabel3 = new javax.swing.JLabel();
        txt_bar = new control.JTextBox(20);
        jLabel4 = new javax.swing.JLabel();
        txt_name = new control.JTextBox(20);
        jLabel5 = new javax.swing.JLabel();
        txt_price = new control.JTextBox(20);
        jLabel6 = new javax.swing.JLabel();
        cmx_status = new control.JMyCompo();
        jLabel7 = new javax.swing.JLabel();
        cmx_cat = new control.JMyCompo();
        jLabel8 = new javax.swing.JLabel();
        cmx_brand = new control.JMyCompo();
        btn_add = new control.JMyButton();
        btn_up = new control.JMyButton();
        btn_del = new control.JMyButton();
        btn_clear = new control.JMyButton();
        btn_display = new control.JMyButton();
        btn_back = new control.JMyButton();
        jLabel9 = new javax.swing.JLabel();
        rad_ID = new javax.swing.JRadioButton();
        rad_prod = new javax.swing.JRadioButton();
        rad_stat = new javax.swing.JRadioButton();
        txt_search = new control.JTextBox(20);
        btn_search = new control.JMyButton();
        rad_cat = new javax.swing.JRadioButton();
        rad_brand = new javax.swing.JRadioButton();
        rad_price = new javax.swing.JRadioButton();
        rad_bar = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        btn_AddCat = new control.JMyButton();
        btn_AddBrand = new control.JMyButton();
        jLabel10 = new javax.swing.JLabel();
        txt_qty = new control.JTextBox(20);
        user = new javax.swing.JLabel();
        log = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Stock");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("Product ID :");

        txt_ID.setEditable(false);
        txt_ID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setText("BarCode :");

        txt_bar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_bar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_barKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setText("Product :");

        txt_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nameKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setText("Price :");

        txt_price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_priceKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setText("Status :");

        cmx_status.setMaximumRowCount(2);
        cmx_status.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmx_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmx_statusActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setText("Category :");

        cmx_cat.setMaximumRowCount(50);
        cmx_cat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmx_cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmx_catActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel8.setText("Brand :");

        cmx_brand.setMaximumRowCount(100);
        cmx_brand.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmx_brand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmx_brandActionPerformed(evt);
            }
        });

        btn_add.setText("ADD");
        btn_add.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_up.setText("Update");
        btn_up.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_upActionPerformed(evt);
            }
        });

        btn_del.setText("Delete");
        btn_del.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delActionPerformed(evt);
            }
        });

        btn_clear.setText("Clear");
        btn_clear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_display.setText("Display All");
        btn_display.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_displayActionPerformed(evt);
            }
        });

        btn_back.setText("Back");
        btn_back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel9.setText("Search by :");

        rad_ID.setBackground(new java.awt.Color(255, 255, 255));
        rad_ID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rad_ID.setText("ID");

        rad_prod.setBackground(new java.awt.Color(255, 255, 255));
        rad_prod.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rad_prod.setText("Product");

        rad_stat.setBackground(new java.awt.Color(255, 255, 255));
        rad_stat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rad_stat.setText("Status");

        txt_search.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_searchKeyPressed(evt);
            }
        });

        btn_search.setText("Search");
        btn_search.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        rad_cat.setBackground(new java.awt.Color(255, 255, 255));
        rad_cat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rad_cat.setText("Category");

        rad_brand.setBackground(new java.awt.Color(255, 255, 255));
        rad_brand.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rad_brand.setText("Brand");

        rad_price.setBackground(new java.awt.Color(255, 255, 255));
        rad_price.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rad_price.setText("Price");

        rad_bar.setBackground(new java.awt.Color(255, 255, 255));
        rad_bar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rad_bar.setText("BarCode");

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Product", "Category ID", "Category", "Brand ID", "Brand", "Price", "Qty", "BarCode", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        tbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        btn_AddCat.setText("ADD");
        btn_AddCat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_AddCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddCatActionPerformed(evt);
            }
        });

        btn_AddBrand.setText("ADD");
        btn_AddBrand.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_AddBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddBrandActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel10.setText("Qty :");

        txt_qty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_qtyKeyPressed(evt);
            }
        });

        user.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        user.setText("jLabel11");

        log.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        log.setText("Logged as :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(btn_display, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(24, 24, 24)
                                        .addComponent(cmx_status, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(54, 54, 54)
                                        .addComponent(btn_up, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_del, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(24, 24, 24)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(txt_qty, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addComponent(txt_bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8))
                                        .addGap(24, 24, 24)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cmx_brand, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btn_AddBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cmx_cat, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btn_AddCat, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(log)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(user)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rad_ID)
                                .addGap(10, 10, 10)
                                .addComponent(rad_prod)))
                        .addGap(14, 14, 14)
                        .addComponent(rad_stat)
                        .addGap(18, 18, 18)
                        .addComponent(rad_cat)
                        .addGap(10, 10, 10)
                        .addComponent(rad_brand)
                        .addGap(10, 10, 10)
                        .addComponent(rad_price)
                        .addGap(10, 10, 10)
                        .addComponent(rad_bar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rad_ID)
                            .addComponent(rad_prod)
                            .addComponent(rad_stat)
                            .addComponent(rad_cat)
                            .addComponent(rad_brand)
                            .addComponent(rad_price)
                            .addComponent(jLabel9)
                            .addComponent(rad_bar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(log)
                            .addComponent(user))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txt_qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cmx_cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_AddCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cmx_brand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_AddBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cmx_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_up, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_del, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_display, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(11, 11, 11)))
                .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Product p = new Product();

    private void clear() {
        Tools.clear(this);
        txt_bar.requestFocus();
        btn_add.setEnabled(true);
        btn_up.setEnabled(false);
        btn_del.setEnabled(false);

        txt_ID.setText(p.getAutoNumber());
    }

    private void set() {
        String cat = cmx_cat.getSelectedItem().toString();
        String brand = cmx_brand.getSelectedItem().toString();
        int catID = Integer.parseInt(C.getValueByName(cat));
        int BranID = Integer.parseInt(B.getValueByName(brand));

        p.setID(Integer.parseInt(txt_ID.getText()));
        p.setBarcode(txt_bar.getText());
        p.setName(txt_name.getText());
        p.setPrice(Double.parseDouble(txt_price.getText()));
        p.setQty(Integer.parseInt(txt_qty.getText()));
        p.setStatus(cmx_status.getSelectedItem().toString());
        p.setCat_ID(catID);
        p.setBrand_ID(BranID);
    }

    private boolean checkfoundation() {
        boolean check = db.database.checkinsertion(txt_bar.getText());
        return check;
    }

    private void add() {
        checkfoundation();
        char str[] = txt_price.getText().toCharArray();
        for (int i = 0; i < str.length; i++) {
            if (!(str[i] == '.' || str[i] == '1' || str[i] == '2' || str[i] == '3' || str[i] == '4' || str[i] == '5' || str[i] == '6' || str[i] == '7' || str[i] == '8' || str[i] == '9' || str[i] == '0')) {
                Tools.msg("Can't save Alphabetic in this field");
                txt_price.setText("");
                txt_price.requestFocus();
                break;
            }
        }
        char strqty[] = txt_qty.getText().toCharArray();
        for (int i = 0; i < strqty.length; i++) {
            if (!(strqty[i] == '1' || strqty[i] == '2' || strqty[i] == '3' || strqty[i] == '4' || strqty[i] == '5' || strqty[i] == '6' || strqty[i] == '7' || strqty[i] == '8' || strqty[i] == '9' || strqty[i] == '0')) {
                Tools.msg("Can't save Alphabetic in this field");
                txt_qty.setText("");
                txt_qty.requestFocus();
                break;
            }
        }
        if ("".equals(txt_bar.getText())) {
        } else {
            set();
            p.add();
            clear();
            p.selectAll(tbl);
        }
    }

    private void update() {
        char str[] = txt_price.getText().toCharArray();
        for (int i = 0; i < str.length; i++) {
            if (!(str[i] == '.' || str[i] == '1' || str[i] == '2' || str[i] == '3' || str[i] == '4' || str[i] == '5' || str[i] == '6' || str[i] == '7' || str[i] == '8' || str[i] == '9' || str[i] == '0')) {
                Tools.msg("Can't save Alphabetic in this field");
                txt_price.setText("");
                txt_price.requestFocus();
                break;
            }
        }
        char strqty[] = txt_qty.getText().toCharArray();
        for (int i = 0; i < strqty.length; i++) {
            if (!(strqty[i] == '1' || strqty[i] == '2' || strqty[i] == '3' || strqty[i] == '4' || strqty[i] == '5' || strqty[i] == '6' || strqty[i] == '7' || strqty[i] == '8' || strqty[i] == '9' || strqty[i] == '0')) {
                Tools.msg("Can't save Alphabetic in this field");
                txt_qty.setText("");
                txt_qty.requestFocus();
                break;
            }
        }
        if ("".equals(txt_price.getText()) || "".equals(txt_qty.getText())) {
        } else {
            set();
            p.update();
            clear();
            p.selectAll(tbl);
        }
    }

    private void delete() {
        if (Tools.ConfirmMsg("Are You Sure You Want To Delete this Product permanently?")) {
            set();
            p.delete();
            clear();
            p.selectAll(tbl);
        }
    }

    private void search() {
        String txtSer;
        String query = "SELECT * FROM `project_data` WHERE ";
        if (rad_ID.isSelected()) {
            txtSer = Tools.getnum(txt_search.getText());
            query += "ID like '%" + txtSer + "%'";
        } else if (rad_prod.isSelected()) {
            txtSer = Tools.removenum(txt_search.getText());
            query += "ProName like '%" + txtSer + "%'";
        } else if (rad_bar.isSelected()) {
            txtSer = Tools.getnum(txt_search.getText());
            query += "Barcode like '%" + txtSer + "%'";
        } else if (rad_brand.isSelected()) {
            query += "Brand_ID like '%" + txt_search.getText() + "%'";
        } else if (rad_cat.isSelected()) {
            query += "Cat_ID like '%" + txt_search.getText() + "%'";
        } else if (rad_price.isSelected()) {
            txtSer = Tools.getnum(txt_search.getText());
            query += "Price like '%" + txtSer + "%'";
        } else {
            txtSer = Tools.removenum(txt_search.getText());
            query += "Statuss like '%" + txtSer + "%'";
        }
        p.getCustom(query, tbl);
    }

    private void cmx_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmx_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmx_statusActionPerformed

    private void cmx_catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmx_catActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmx_catActionPerformed

    private void cmx_brandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmx_brandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmx_brandActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        add();
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_upActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_btn_upActionPerformed

    private void btn_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delActionPerformed
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_btn_delActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_displayActionPerformed
        // TODO add your handling code here:
        p.selectAll(tbl);
    }//GEN-LAST:event_btn_displayActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        main m = new main(username);
        m.setTitle("Main Menu");
        this.dispose();
        Tools.open(m);
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_btn_searchActionPerformed

    Category C = new Category();
    Brand B = new Brand();

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        btn_group.add(rad_ID);
        btn_group.add(rad_bar);
        btn_group.add(rad_brand);
        btn_group.add(rad_cat);
        btn_group.add(rad_price);
        btn_group.add(rad_prod);
        btn_group.add(rad_stat);
        p.selectAll(tbl);
        tbl.getTableHeader().setReorderingAllowed(false);
        clear();
        db.database.FillCombo("category", "Category", "Statuss = 'Active'", cmx_cat);
        db.database.FillCombo("brand", "Brand", "Statuss = 'Active'", cmx_brand);
        btn_up.setEnabled(false);
        btn_del.setEnabled(false);
        btn_add.setEnabled(true);
        txt_bar.requestFocus();
        user.setText(username);
    }//GEN-LAST:event_formWindowOpened

    private void btn_AddCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddCatActionPerformed
        // TODO add your handling code here:
        int CatNO = Integer.parseInt(C.getAutoNumber());
        String CatName = (String) Tools.InputBox("Enter the category Name :");
        String CatStat = (String) Tools.InputBox("Enter the Status of this Category :");
        String name = Tools.removenum(CatName);
        String status = Tools.removenum(CatStat);
        if ("".equals(name)||"".equals(status) || "".equals(CatName) || "".equals(CatStat)) {
            Tools.msg("Can't save Catgory with empty data");
        } else {
            C.setID(CatNO);
            C.setName(name);
            C.setStatus(status);
            C.add();
            db.database.FillCombo("category", "Category", "Statuss = 'Active'", cmx_cat);
        }
    }//GEN-LAST:event_btn_AddCatActionPerformed

    @Override
    public void setVisible(boolean b) {
        super.setVisible(b); //To change body of generated methods, choose Tools | Templates.
    }

    private void btn_AddBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddBrandActionPerformed
        // TODO add your handling code here:
        int BrandNO = Integer.parseInt(B.getAutoNumber());
        String BrandName = (String) Tools.InputBox("Enter the Brand Name :");
        String BrandStat = (String) Tools.InputBox("Enter the Status of this Brand :");
        String name = Tools.removenum(BrandName);
        String status = Tools.removenum(BrandStat);
        if ("".equals(BrandName) || "".equals(BrandStat) || "".equals(name) || "".equals(status)) {
            Tools.msg("Can't save Brand with empty data");
        } else {
            B.setID(BrandNO);
            B.setName(BrandName);
            B.setStatus(BrandStat);
            B.add();
            db.database.FillCombo("brand", "Brand", "Statuss = 'Active'", cmx_brand);
        }
    }//GEN-LAST:event_btn_AddBrandActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        // TODO add your handling code here:
        try {
            int row = tbl.getSelectedRow();
            txt_ID.setText(tbl.getValueAt(row, 0).toString());
            txt_name.setText(tbl.getValueAt(row, 1).toString());
            cmx_cat.setSelectedItem(tbl.getValueAt(row, 3).toString());
            cmx_brand.setSelectedItem(tbl.getValueAt(row, 5).toString());
            txt_price.setText(tbl.getValueAt(row, 6).toString());
            txt_qty.setText(tbl.getValueAt(row, 7).toString());
            //cmx_brand.setSelectedItem(p.getNameByValue(tbl.getValueAt(row, 3)));
            //txt_qty.setText(tbl.getValueAt(row, 6).toString());
            txt_bar.setText(tbl.getValueAt(row, 8).toString());
            cmx_status.setSelectedItem(tbl.getValueAt(row, 9).toString());
            btn_add.setEnabled(false);
            btn_up.setEnabled(true);
            btn_del.setEnabled(true);
        } catch (Exception ex) {
            Tools.msg(ex.getMessage());
        }
    }//GEN-LAST:event_tblMouseClicked

    private void txt_qtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_qtyKeyPressed
        // TODO add your handling code here:
        if (btn_add.isEnabled()) {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                add();
            }
        } else if (!btn_add.isEnabled()) {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                update();
            }
        }
    }//GEN-LAST:event_txt_qtyKeyPressed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        btn_add.setEnabled(true);
        btn_up.setEnabled(false);
        btn_del.setEnabled(false);
        //Tools.clear(this);
        txt_bar.setText("");
        txt_name.setText("");
        txt_price.setText("");
        txt_qty.setText("");
        txt_search.setText("");
        cmx_cat.setSelectedIndex(0);
        cmx_brand.setSelectedIndex(0);
        cmx_status.setSelectedIndex(0);
        
        //p.setID(Integer.parseInt(txt_ID.getText()));
        txt_ID.setText(p.getAutoNumber());
        txt_bar.requestFocus();
    }//GEN-LAST:event_formMouseClicked

    private void txt_priceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_priceKeyPressed
        // TODO add your handling code here:
        if (!btn_add.isEnabled()) {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                update();
            }
        }
    }//GEN-LAST:event_txt_priceKeyPressed

    private void txt_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nameKeyPressed
        // TODO add your handling code here:
        if (!btn_add.isEnabled()) {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                update();
            }
        }
    }//GEN-LAST:event_txt_nameKeyPressed

    private void txt_barKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_barKeyPressed
        // TODO add your handling code here:
        if (!btn_add.isEnabled()) {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                update();
            }
        } else if (btn_add.isEnabled()) {
            if (checkfoundation() == true) {
                txt_name.setText(p.getName(txt_bar.getText()));
                txt_price.setText(p.getPrice(txt_bar.getText()));
                txt_qty.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_barKeyPressed

    private void txt_searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            search();
        }
    }//GEN-LAST:event_txt_searchKeyPressed

    private void tblKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblKeyPressed
        // TODO add your handling code here:
        if (!btn_add.isEnabled()) {
            if (evt.getKeyCode()==KeyEvent.VK_DELETE) {
                delete();
            }
        }
    }//GEN-LAST:event_tblKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private control.JMyButton btn_AddBrand;
    private control.JMyButton btn_AddCat;
    private control.JMyButton btn_add;
    private control.JMyButton btn_back;
    private control.JMyButton btn_clear;
    private control.JMyButton btn_del;
    private control.JMyButton btn_display;
    private javax.swing.ButtonGroup btn_group;
    private control.JMyButton btn_search;
    private control.JMyButton btn_up;
    private control.JMyCompo cmx_brand;
    private control.JMyCompo cmx_cat;
    private control.JMyCompo cmx_status;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel log;
    private javax.swing.JRadioButton rad_ID;
    private javax.swing.JRadioButton rad_bar;
    private javax.swing.JRadioButton rad_brand;
    private javax.swing.JRadioButton rad_cat;
    private javax.swing.JRadioButton rad_price;
    private javax.swing.JRadioButton rad_prod;
    private javax.swing.JRadioButton rad_stat;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txt_ID;
    private javax.swing.JTextField txt_bar;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_price;
    private javax.swing.JTextField txt_qty;
    private javax.swing.JTextField txt_search;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
